---
name: Ejercitación - Introducción a Frontend
locale: es
type: learning
beta: false
teacher_info: ''
language: html
id_format: "%05d"
order:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 7
- 8
- 7
- 9
- 13
- 10
- 13
- 11
- 12
- 14
- 13
private: false
